# Aether pencere animasyonları (picom eklentisi)
backend = "xrender";
vsync = true;
shadow = true; shadow-radius = 10; shadow-opacity = 0.25; shadow-offset-x = -8; shadow-offset-y = -6;
shadow-exclude = [ "class_g = 'i3lock'", "_GTK_FRAME_EXTENTS@" ];
fading = true; fade-in-step = 0.06; fade-out-step = 0.06;
corner-radius = 0;
animations = (
  { triggers = ["open", "show"]; preset = "appear"; duration = 0.18; scale = 0.94; },
  { triggers = ["close", "hide"]; preset = "disappear"; duration = 0.14; scale = 0.94; }
);
