# Aether 2.0 "Orion" — LightDM
[LightDM]
run-directory=/run/lightdm
[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=aether
session-wrapper=/etc/lightdm/Xsession
greeter-hide-users=false
allow-guest=false
