# Aether giriş ekranı
[greeter]
background=/usr/share/aether/wallpapers/nebula.png
user-background=false
theme-name=Aether
icon-theme-name=Adwaita
font-name=JetBrains Mono 10
default-user-image=#aether
indicators=~host;~spacer;~clock;~spacer;~layout;~power
clock-format=%d.%m.%Y  %H:%M
position=50%,center 76%,center
screensaver-timeout=60
hide-user-image=false
round-user-image=false
highlight-logged-user=true
keyboard=
