# Aether 1.0 "Nebula" — LightDM
[LightDM]
run-directory=/run/lightdm
[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=aether
session-wrapper=/usr/bin/lightdm-session
greeter-hide-users=false
allow-guest=false
